import Foundation

final class SecurityDashboardViewModel: ObservableObject {
    @Published var threatAlerts: [ThreatAlert] = [
        ThreatAlert(
            title: "Suspicious Login Attempt",
            detail: "New sign-in from unknown device in Austin, TX.",
            severity: .high,
            timestamp: "2h ago",
            recommendedAction: "Change your account password immediately and enforce multi-factor authentication."
        ),
        ThreatAlert(
            title: "Public Wi-Fi Exposure",
            detail: "Connection detected on unsecured network.",
            severity: .medium,
            timestamp: "5h ago",
            recommendedAction: "Disconnect from public Wi-Fi and use a trusted VPN before accessing sensitive services."
        ),
        ThreatAlert(
            title: "Password Reuse Warning",
            detail: "A saved password matches a known breach.",
            severity: .low,
            timestamp: "1d ago",
            recommendedAction: "Update the reused password and replace it with a unique password generated by a password manager."
        )
    ]

    @Published var protectionTasks: [ProtectionTask] = [
        ProtectionTask(title: "Enable Multi-Factor Authentication", detail: "Protect accounts with a second verification step.", isCompleted: true),
        ProtectionTask(title: "Rotate Critical Passwords", detail: "Update passwords for email and banking accounts.", isCompleted: false),
        ProtectionTask(title: "Review App Permissions", detail: "Revoke unnecessary camera and location access.", isCompleted: true),
        ProtectionTask(title: "Configure Device Auto-Lock", detail: "Set lock timeout to 30 seconds.", isCompleted: false)
    ]

    @Published var securityTips: [SecurityTip] = [
        SecurityTip(title: "Prioritize MFA for High-Value Accounts", detail: "Start with email, banking, and developer tools where account takeover risk is highest.", iconName: "person.badge.shield.checkmark"),
        SecurityTip(title: "Use Unique Passwords", detail: "Adopt a password manager and generate unique credentials for every service.", iconName: "key.fill"),
        SecurityTip(title: "Turn On Breach Monitoring", detail: "Track leaked credentials and rotate impacted passwords immediately.", iconName: "eye.trianglebadge.exclamationmark"),
        SecurityTip(title: "Harden Mobile Browsing", detail: "Avoid unknown links and keep iOS plus browser updates enabled.", iconName: "safari.fill")
    ]

    var securityScore: Int {
        let alertsPenalty = threatAlerts.reduce(0) { partialResult, alert in
            partialResult + penalty(for: alert.severity)
        }
        let taskPenalty = openIssueCount * 8
        return max(0, min(100, 100 - alertsPenalty - taskPenalty))
    }

    var riskLevel: String {
        switch securityScore {
        case 80...100:
            return "Low"
        case 50..<80:
            return "Moderate"
        default:
            return "High"
        }
    }

    var alertCount: Int { threatAlerts.count }

    var openIssueCount: Int {
        protectionTasks.filter { !$0.isCompleted }.count
    }

    var completedTaskCount: Int {
        protectionTasks.filter(\.isCompleted).count
    }

    func toggleTask(_ task: ProtectionTask) {
        guard let index = protectionTasks.firstIndex(where: { $0.id == task.id }) else {
            return
        }
        protectionTasks[index].isCompleted.toggle()
    }

    func resolveAlert(_ alert: ThreatAlert) {
        threatAlerts.removeAll { $0.id == alert.id }
    }

    private func penalty(for severity: ThreatSeverity) -> Int {
        switch severity {
        case .high:
            return 20
        case .medium:
            return 10
        case .low:
            return 5
        }
    }
}
